// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSAc58xMhpzRdD4xQtKxBbkieRh82y2I0',
    appId: '1:559841067643:web:57b59eac58e74cc22a18de',
    messagingSenderId: '559841067643',
    projectId: 'expensetracker-6b9a8',
    authDomain: 'expensetracker-6b9a8.firebaseapp.com',
    storageBucket: 'expensetracker-6b9a8.firebasestorage.app',
    measurementId: 'G-FBSSF83QVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKvl0q7it9HY6GDCdwFwB63DnAiAzesqc',
    appId: '1:559841067643:android:95a4ddc9937191f32a18de',
    messagingSenderId: '559841067643',
    projectId: 'expensetracker-6b9a8',
    storageBucket: 'expensetracker-6b9a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9IEw7ynTIYfp8L4aK3J60gKFgByTy-DE',
    appId: '1:559841067643:ios:8a0fb2ada0028ced2a18de',
    messagingSenderId: '559841067643',
    projectId: 'expensetracker-6b9a8',
    storageBucket: 'expensetracker-6b9a8.firebasestorage.app',
    iosBundleId: 'com.example.nexoeshopee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9IEw7ynTIYfp8L4aK3J60gKFgByTy-DE',
    appId: '1:559841067643:ios:8a0fb2ada0028ced2a18de',
    messagingSenderId: '559841067643',
    projectId: 'expensetracker-6b9a8',
    storageBucket: 'expensetracker-6b9a8.firebasestorage.app',
    iosBundleId: 'com.example.nexoeshopee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA0Flyflvg_SmPrE1rLjlSHSR0V8krWyA',
    appId: '1:559841067643:web:e3df7f87b6010c002a18de',
    messagingSenderId: '559841067643',
    projectId: 'expensetracker-6b9a8',
    authDomain: 'expensetracker-6b9a8.firebaseapp.com',
    storageBucket: 'expensetracker-6b9a8.firebasestorage.app',
    measurementId: 'G-VEXDJ4S8H2',
  );
}
